#!/bin/sh

pre-commit run
mkdir -p build/build-release-ctest
cmake --build ./build/build-release-ctest --target all
cmake -S . -B ./build/build-release-ctest -DCMAKE_BUILD_TYPE=Release
cd ./build/build-release-ctest
ctest -j 4